### PR TITLE
Fix crash & improve clipboard window usability

### PR DESCRIPTION
**Pull request by pjrobertson**
I built QS to debug it just now, and got a warning in Xcode that view stuff was being being run on a non-main thread (that's pretty cool that Xcode tells you explicitly now).

Fixing this should fix the majority of the Clipboard plugin crashes. I'd previously tried in vain to fix them, but I still stupidly used a non-main thread to run all NSView update stuff on. Duh

And then the inevitable... when you start editing QS code you find 101 other things that need doing, so I:

1. Finally got the "keep the most rich version of an object in the clipboard" feature working properly
2. Avoided getting (null) items in the clipboard (e.g. from 1Password)
3. Fixed the Clipboard window to scroll back to the top when you double click and paste an object from it.

### CODE REVIEW

**Comment by skurfer** [comment]
Awesome. I’ll take a look.

**Comment by skurfer** [comment]
So is this what was causing the calls to the main thread from QSLibrarian? In my brief Catalina testing, that was crashing QS on launch, but I didn’t have time to track it down.

**Comment by pjrobertson** [comment]
I don't think the Clipboard Plugin will call through to QSLibrarian, other than perhaps the fact you're adding new objects to the catalog. This fix here is solving crashes occurring from running main-thread view updates on a non-main thread.

Do you mean you were getting the crash *with* these changes?

**Comment by skurfer** [comment]
> Do you mean you were getting the crash *with* these changes?

No, I haven’t been on Catalina much. I’m sure this will help out there, though.

**Comment by pjrobertson** [comment]
@skurfer can I merge this PR/any issues? I want to make some more changes to the clipboard plugin related to Quicksilver/quicksilver#2501

**Comment by pjrobertson** [comment]
Thanks :)

**Pull request merged**
